### ISSUE TITLE
DigitalNameplate should not use "example.com" id

### ISSUE THREAD

**Issue by shuebner** [admin-shell-io/submodel-templates#20]
DigitalNameplate V2.0 has an id of `www.example.com/ids/sm/1225_9020_5022_1974`:
![image](https://user-images.githubusercontent.com/1770684/219310048-82c2e95b-ab30-41d4-99a0-67c860554e19.png)

Why would a standardized submodel template be published with "example" in its id?

This is suspicious and inconsistent with e. g. TechnicalData V1.2, which has a more appropriate id `https://admin-shell.io/ZVEI/TechnicalData/Submodel/1/2`.

**Comment by BirgitBoss** [comment]
This is true, since this is the template ID and not an example for a submodel instance. In the latter case it would be ok.
For HandoverDocumentation it is https://admin-shell.io/IDTA02004-1-2

I recommend something like **urn:io.admin-shell:IDTA02006-2-0** or **https://admin-shell.io/IDTA02006-2-0**

**Comment by BirgitBoss** [comment]
same holds for SMT HandoverDocumentation

**Comment by Rudra-sandeep** [comment]
@shuebner Check the latest version of the SMT the issue is fixed
