### ISSUE TITLE
All Submodel-Templates have wrong Relationship Type in *.rels

### ISSUE THREAD

**Issue by zrgt** [admin-shell-io/submodel-templates#61]
I tried to open submodel-templates with[ AAS Manager ](https://github.com/rwth-iat/aas_manager) and [BaSyx-Python-SDK](https://github.com/eclipse-basyx/basyx-python-sdk). Unfortunately there is still the bug with .aasx relationships in ALL submodel-templates.

The bug is also described in the following issue:
https://github.com/eclipse-aaspe/aaspe/issues/161

According to the issue, the bug has been fixed in AASPE, but it still exists in serialized submodel-templates. The problem now is that no Basyx SDK can work with the templates without using a fix tool.

We need a fix ASAP, as it is a huge Compatibility bug which effects multiple SDKs.

**Comment by juileetikekar** [comment]
Hi @zrgt,

Thank you for raising the issue !

The issue is known to us and has been caused because of a missing commit during the migration of AASX Package Explorer from admin-shell-io to Eclipse. We have fixed the issue in the Eclipse package explorer.  However, before publishing the submodel-templates, we are executing some quality checks. As soon as the quality checks are passed, we will publish the templates again.

**Comment by juileetikekar** [comment]
Hi @zrgt,
The issue with wrong relationship has been fixed and the submodel templates have been upgraded.
